export interface Singer {
  id: string;
  name: string;
  categories: string[];
  followers: number | null;
  rating: number;
  image: string;
  genre: string;
  ordinal: number;
}

export const SINGER_DATABASE: Singer[] = [
  {
    id: "1",
    name: "Arijit Singh",
    categories: ["Hindi", "English"],
    followers: 25_000_000,
    rating: 4.7,
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Arijit_5th_GiMA_Awards.jpg",
    genre: "Hindi",
    ordinal: 1,
  },
  {
    id: "2",
    name: "Pritam",
    categories: ["Hindi", "English"],
    followers: 18_000_000,
    rating: 4.5,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/39/Pritam_Chakraborty.jpg",
    genre: "Hindi",
    ordinal: 2,
  },
  {
    id: "3",
    name: "Yo Yo Honey Singh",
    categories: ["Hindi", "English"],
    followers: 12_000_000,
    rating: 4.2,
    image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Yo_Yo_Honey_Singh.jpg",
    genre: "Hindi",
    ordinal: 3,
  },
  {
    id: "4",
    name: "Neeti Mohan",
    categories: ["Hindi"],
    followers: 8_000_000,
    rating: 4.6,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Neeti_Mohan.jpg",
    genre: "Hindi",
    ordinal: 4,
  },
  {
    id: "5",
    name: "Shekhar Ravjiani",
    categories: ["Hindi", "English"],
    followers: 9_000_000,
    rating: 4.4,
    image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Shekhar_Ravjiani.jpg",
    genre: "Hindi",
    ordinal: 5,
  },
  {
    id: "6",
    name: "Caroliene",
    categories: ["English"],
    followers: 5_000_000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    genre: "English",
    ordinal: 6,
  },
  {
    id: "7",
    name: "Kashmira Shroff",
    categories: ["English"],
    followers: 4_500_000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    genre: "English",
    ordinal: 7,
  },
  {
    id: "8",
    name: "Taylor Swift",
    categories: ["English"],
    followers: 4_200_000,
    rating: 4.3,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Taylor_Swift_2_-_2019_by_Glenn_Francis.jpg",
    genre: "Pop / Country",
    ordinal: 8,
  },
  {
    id: "9",
    name: "Drake",
    categories: ["English"],
    followers: 6_800_000,
    rating: 4.1,
    image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Drake_at_the_Velvet_Underground.jpg",
    genre: "Hip Hop",
    ordinal: 9,
  },
  {
    id: "10",
    name: "Billie Eilish",
    categories: ["English"],
    followers: 7_200_000,
    rating: 4.9,
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Billie_Eilish_2019_by_Glenn_Francis.jpg",
    genre: "Alternative",
    ordinal: 10,
  },
  {
    id: "11",
    name: "Fazilpuria",
    categories: ["Haryanvi"],
    followers: 5_500_000,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    genre: "Haryanvi Pop",
    ordinal: 11,
  },
  {
    id: "12",
    name: "Elvish Yadav",
    categories: ["Haryanvi"],
    followers: 4_800_000,
    rating: 4.1,
    image: "https://upload.wikimedia.org/wikipedia/commons/7/72/Elvish_Yadav.jpg",
    genre: "Haryanvi Pop",
    ordinal: 12,
  },
  {
    id: "13",
    name: "Raj Mawar",
    categories: ["Haryanvi"],
    followers: 3_200_000,
    rating: 4.0,
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80",
    genre: "Haryanvi Pop",
    ordinal: 13,
  },
  {
    id: "14",
    name: "Khesari Lal Yadav",
    categories: ["Bhojpuri"],
    followers: 6_100_000,
    rating: 4.2,
    image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Khesari_Lal_Yadav.jpg",
    genre: "Bhojpuri Folk",
    ordinal: 14,
  },
  {
    id: "15",
    name: "Pawan Singh",
    categories: ["Bhojpuri"],
    followers: 4_300_000,
    rating: 4.0,
    image: "https://upload.wikimedia.org/wikipedia/commons/7/71/Pawan_Singh.jpg",
    genre: "Bhojpuri Pop",
    ordinal: 15,
  },
  {
    id: "16",
    name: "Kavita Chawla",
    categories: ["Bhojpuri"],
    followers: 2_900_000,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    genre: "Bhojpuri Folk",
    ordinal: 16,
  },
];