/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg": "var(--background)",
        "bg-sec": "var(--background-secondary)",
        "bg-ter": "var(--background-tertiary)",
        "card": "var(--card)",
        "card-hover": "var(--card-hover)",
        "surface": "var(--surface)",
        "pri": "var(--text-primary)",
        "sec": "var(--text-secondary)",
        "muted": "var(--text-muted)",
        "primary": "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-light": "var(--primary-light)",
        "secondary": "var(--secondary)",
        "secondary-hover": "var(--secondary-hover)",
        "accent": "var(--accent)",
        "border": "var(--border)",
        "border-light": "var(--border-light)",
        "border-glow": "var(--border-glow)",
        "input": "var(--input-bg)",
        "input-border": "var(--input-border)",
        "input-focus": "var(--input-focus)",
        "success": "var(--success)",
        "warning": "var(--warning)",
        "error": "var(--error)",
        "blob-gold": "var(--primary)",
        "blob-gold-sec": "var(--secondary)",
        "blob-gold-ter": "var(--accent)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        primary: "var(--shadow-premium)",
        cyan: "var(--shadow-premium)",
      },
      borderRadius: {
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
};